name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/deploy-cloudrun.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Configure gcloud defaults
        run: |
          gcloud config set run/region "$GCP_REGION"
          gcloud config set project "$GCP_PROJECT"

      - name: Build and push container image
        run: |
          IMAGE="gcr.io/${GCP_PROJECT}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}"
          gcloud builds submit Server --tag "$IMAGE"
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$CLOUD_RUN_SERVICE" \
            --image "$IMAGE" \
            --platform managed \
            --region "$GCP_REGION" \
            --allow-unauthenticated \
            --set-env-vars "SUPABASE_DB_URL=${SUPABASE_DB_URL},JWT_SECRET=${JWT_SECRET}"

      - name: Wait for service readiness
        run: |
          SERVICE_URL=$(gcloud run services describe "$CLOUD_RUN_SERVICE" --region "$GCP_REGION" --format 'value(status.url)')
          echo "SERVICE_URL=$SERVICE_URL" >> "$GITHUB_ENV"
          echo "Service URL: $SERVICE_URL"

      - name: Verify health endpoint
        run: |
          curl --retry 5 --retry-connrefused --fail "$SERVICE_URL/health"
